# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'child1.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(820, 620)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(170, 70, 531, 361))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(120, 40, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Adobe Caslon Pro Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.weatherComboBox_2 = QtWidgets.QComboBox(self.groupBox)
        self.weatherComboBox_2.setGeometry(QtCore.QRect(180, 40, 221, 22))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.weatherComboBox_2.setFont(font)
        self.weatherComboBox_2.setObjectName("weatherComboBox_2")
        self.weatherComboBox_2.addItem("")
        self.weatherComboBox_2.addItem("")
        self.weatherComboBox_2.addItem("")
        self.weatherComboBox_2.addItem("")
        self.weatherComboBox_2.addItem("")
        self.weatherComboBox_2.addItem("")
        self.weatherComboBox_2.addItem("")
        self.weatherComboBox_2.addItem("")
        self.weatherComboBox_2.addItem("")
        self.weatherComboBox_2.addItem("")
        self.weatherComboBox_2.addItem("")
        self.weatherComboBox_2.addItem("")
        self.weatherComboBox_2.addItem("")
        self.weatherComboBox_2.addItem("")
        self.weatherComboBox_2.addItem("")
        self.weatherComboBox_2.addItem("")
        self.resultText_2 = QtWidgets.QTextEdit(self.groupBox)
        self.resultText_2.setGeometry(QtCore.QRect(100, 110, 341, 211))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.resultText_2.setFont(font)
        self.resultText_2.setObjectName("resultText_2")
        self.clearBtn = QtWidgets.QPushButton(Form)
        self.clearBtn.setGeometry(QtCore.QRect(490, 460, 75, 23))
        self.clearBtn.setObjectName("clearBtn")
        self.queryBtn = QtWidgets.QPushButton(Form)
        self.queryBtn.setGeometry(QtCore.QRect(270, 460, 75, 23))
        self.queryBtn.setObjectName("queryBtn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "查询城市天气"))
        self.label_2.setText(_translate("Form", "城市："))
        self.weatherComboBox_2.setItemText(0, _translate("Form", "北京"))
        self.weatherComboBox_2.setItemText(1, _translate("Form", "广州"))
        self.weatherComboBox_2.setItemText(2, _translate("Form", "汕头"))
        self.weatherComboBox_2.setItemText(3, _translate("Form", "西安"))
        self.weatherComboBox_2.setItemText(4, _translate("Form", "上海"))
        self.weatherComboBox_2.setItemText(5, _translate("Form", "天津"))
        self.weatherComboBox_2.setItemText(6, _translate("Form", "杭州"))
        self.weatherComboBox_2.setItemText(7, _translate("Form", "武汉"))
        self.weatherComboBox_2.setItemText(8, _translate("Form", "南京"))
        self.weatherComboBox_2.setItemText(9, _translate("Form", "深圳"))
        self.weatherComboBox_2.setItemText(10, _translate("Form", "厦门"))
        self.weatherComboBox_2.setItemText(11, _translate("Form", "长沙"))
        self.weatherComboBox_2.setItemText(12, _translate("Form", "合肥"))
        self.weatherComboBox_2.setItemText(13, _translate("Form", "太原"))
        self.weatherComboBox_2.setItemText(14, _translate("Form", "郑州"))
        self.weatherComboBox_2.setItemText(15, _translate("Form", "苏州"))
        self.clearBtn.setText(_translate("Form", "清空"))
        self.queryBtn.setText(_translate("Form", "查询"))

